    # -*- coding: utf-8 -*-
"""
Created on Tue Oct 10

@author: jaehyuk
"""

import numpy as np
import scipy.stats as ss
import scipy.optimize as sopt
from . import normal
from . import bsm
import pyfeng as pf

'''
MC model class for Beta=1
'''
class ModelBsmMC:
    beta = 1.0   # fixed (not used)
    vov, rho = 0.0, 0.0
    sigma, intr, divr = None, None, None
    bsm_model = None
    '''
    You may define more members for MC: time step, etc
    '''
    
    def __init__(self, sigma, vov=0, rho=0.0, beta=1.0, intr=0, divr=0):
        self.sigma = sigma
        self.vov = vov
        self.rho = rho
        self.intr = intr
        self.divr = divr
        self.bsm_model = pf.Bsm(sigma, intr=intr, divr=divr)
        
    def bsm_vol(self, strike, spot, texp=None, sigma=None):
        ''''
        From the price from self.price() compute the implied vol
        this is the opposite of bsm_vol in ModelHagan class
        use bsm_model
       
        sigma = self.sigma if(sigma is None) else sigma
        texp = self.texp if(texp is None) else texp
        
        price = self.price(strike, spot, texp, sigm)
        bs = bsm.Model(texp, None, self.intr, self.divr)
        result = bs.impvol(price, strike, spot, texp, cp_sign=1)
         '''
        return 0
    
    def price(self, strike, spot, texp=None, sigma=None, cp=1):
        '''
        Your MC routine goes here
        Generate paths for vol and price first. Then get prices (vector) for all strikes
        You may fix the random number seed
        '''
        sigma = self.sigma if(sigma is None) else sigma
        texp = self.texp if(texp is None) else texp
        div_fac = np.exp(-texp*self.divr)
        disc_fac = np.exp(-texp*self.intr)
        forward = spot / disc_fac * div_fac
        
        np.random.seed(12345)
        
        step, M = 0.01, 10000
        N = int(texp / step)
        
        X = np.random.multivariate_normal([0,0], [[1, self.rho], [self.rho, 1]], (M,N), 'raise')
        W = X[:,:,0]
        Z = X[:,:,1]
        
        sigma_list = np.cumprod(np.exp(self.vov * np.sqrt(step) * Z - 0.5 * (self.vov ** 2) * step), axis=1) * self.sigma 
        ## we will generate a waste sigma since S_k+1 is generated by sigma_k and W_k
        sigma_list = sigma_list[:,:-1]
        log_S_1 = np.log(forward) + self.sigma * W[:,0] * np.sqrt(step) - 0.5 * (self.sigma ** 2) * step
        stock_price_list = np.cumsum(sigma_list * W[:,1:] * np.sqrt(step) - 0.5 * sigma_list * sigma_list * step, axis=1) + log_S_1[:,None]
        price_list = np.fmax(np.exp(stock_price_list[:,-1])-strike[:,None],0)
        price = disc_fac * cp * np.mean(price_list,axis=1)
        
        return price

'''
MC model class for Beta=0
'''
class ModelNormalMC:
    beta = 0.0   # fixed (not used)
    vov, rho = 0.0, 0.0
    sigma, intr, divr = None, None, None
    normal_model = None
    
    def __init__(self, sigma, vov=0, rho=0.0, beta=0.0, intr=0, divr=0):
        self.sigma = sigma
        self.vov = vov
        self.rho = rho
        self.intr = intr
        self.divr = divr
        self.normal_model = pf.Norm(sigma, intr=intr, divr=divr)
        
    def norm_vol(self, strike, spot, texp=None, sigma=None):
        ''''
        From the price from self.price() compute the implied vol
        this is the opposite of normal_vol in ModelNormalHagan class
        use normal_model 
        '''
        return 0
        
    def price(self, strike, spot, texp=None, sigma=None, cp=1):
        '''
        Your MC routine goes here
        Generate paths for vol and price first. Then get prices (vector) for all strikes
        You may fix the random number seed
        '''
        sigma = self.sigma if(sigma is None) else sigma
        texp = self.texp if(texp is None) else texp
          
        div_fac = np.exp(-texp*self.divr)
        disc_fac = np.exp(-texp*self.intr)
        forward = spot / disc_fac * div_fac
        
        np.random.seed(12345)
        
        step, M = 0.01, 10000
        N = int(texp / step)
        
        X = np.random.multivariate_normal([0,0], [[1, self.rho], [self.rho, 1]], (M,N), 'raise')
        W = X[:,:,0]
        Z = X[:,:,1]
        
        sigma_list = np.cumprod(np.exp(self.vov * np.sqrt(step) * Z - 0.5 * (self.vov ** 2) * step), axis=1) * self.sigma
        ## we will generate a waste sigma since S_k+1 is generated by sigma_k and W_k
        S_1 = forward + self.sigma * W[:,0] * np.sqrt(step)
        stock_price_list = np.cumsum(sigma_list[:,:-1] * W[:,1:] * np.sqrt(step), axis=1) + S_1[:,None]
        price_list = np.fmax(stock_price_list[:,-1]-strike[:,None],0)
        price = disc_fac * cp * np.mean(price_list, axis=1)
        
        return price

'''
Conditional MC model class for Beta=1
'''
class ModelBsmCondMC:
    beta = 1.0   # fixed (not used)
    vov, rho = 0.0, 0.0
    sigma, intr, divr = None, None, None
    bsm_model = None
    '''
    You may define more members for MC: time step, etc
    '''
    
    def __init__(self, sigma, vov=0, rho=0.0, beta=1.0, intr=0, divr=0):
        self.sigma = sigma
        self.vov = vov
        self.rho = rho
        self.intr = intr
        self.divr = divr
        self.bsm_model = pf.Bsm(sigma, intr=intr, divr=divr)
        
    def bsm_vol(self, strike, spot, texp=None):
        ''''
        From the price from self.price() compute the implied vol
        this is the opposite of bsm_vol in ModelHagan class
        use bsm_model
        should be same as bsm_vol method in ModelBsmMC (just copy & paste)
        '''
        return 0
    
    def price(self, strike, spot, texp=None, cp=1):
        '''
        Your MC routine goes here
        Generate paths for vol only. Then compute integrated variance and BSM price.
        Then get prices (vector) for all strikes
        You may fix the random number seed
        ''' 
        div_fac = np.exp(-texp*self.divr)
        disc_fac = np.exp(-texp*self.intr)
        forward = spot / disc_fac * div_fac
        
        np.random.seed(12345)
        
        step, M = 0.01, 10000
        N = int(texp / step)
        
        Z = np.random.normal(size=(M,N))
        
        sigma_list = np.cumprod(np.exp(self.vov * np.sqrt(step) * Z - 0.5 * (self.vov ** 2) * step), axis=1) * self.sigma
        if N//2 == 0:
            even = list(range(2,N,2))
            odd = list(range(1,N,2))
            I_T = (self.sigma**2 +sigma_list[:,-1]**2+2*np.sum(sigma_list[:,even]**2, axis=1)+4*np.sum(sigma_list[:,odd]**2, axis=1))/(3*N)/(self.sigma**2)
        else:
            I_T = np.mean(sigma_list ** 2, axis = 1) / (self.sigma ** 2)
        S_0 = forward * np.exp(self.rho / self.vov * (sigma_list[:,-1] - self.sigma) - (self.rho * self.sigma) ** 2 * texp /2 * I_T)
        sigma_BS = self.sigma * np.sqrt((1-self.rho ** 2) * I_T)
        price_list = bsm.price(strike[:,None], S_0, texp, sigma_BS , intr=0.0, divr=0.0, cp_sign=cp)
        price = np.mean(price_list, axis=1)
        return price
        
        return price

'''
Conditional MC model class for Beta=0
'''
class ModelNormalCondMC:
    beta = 0.0   # fixed (not used)
    vov, rho = 0.0, 0.0
    sigma, intr, divr = None, None, None
    normal_model = None
    
    def __init__(self, sigma, vov=0, rho=0.0, beta=0.0, intr=0, divr=0):
        self.sigma = sigma
        self.vov = vov
        self.rho = rho
        self.intr = intr
        self.divr = divr
        self.normal_model = pf.Norm(sigma, intr=intr, divr=divr)
        
    def norm_vol(self, strike, spot, texp=None):
        ''''
        From the price from self.price() compute the implied vol
        this is the opposite of normal_vol in ModelNormalHagan class
        use normal_model
        should be same as norm_vol method in ModelNormalMC (just copy & paste)
        '''
        return 0
        
    def price(self, strike, spot, texp=None, cp=1):
        '''
        Your MC routine goes here
        Generate paths for vol only. Then compute integrated variance and normal price.
        You may fix the random number seed
        '''
        div_fac = np.exp(-texp*self.divr)
        disc_fac = np.exp(-texp*self.intr)
        forward = spot / disc_fac * div_fac
        
        np.random.seed(12345)
        
        step, M = 0.01, 10000
        N = int(texp / step)
        
        Z = np.random.normal(size=(M,N))
        
        sigma_list = np.cumprod(np.exp(self.vov * np.sqrt(step) * Z - 0.5 * (self.vov ** 2) * step), axis=1) * self.sigma
        I_T = (np.mean(sigma_list ** 2, axis=1) + (self.sigma ** 2 - sigma_list[:,-1] ** 2)/ (2 * N)) / (self.sigma ** 2)
        S_0 = forward + self.rho / self.vov * (sigma_list[:,-1] - self.sigma)
        sigma_N = self.sigma * np.sqrt((1-self.rho ** 2) * I_T)
        price_list = normal.price(strike[:,None], S_0, texp, sigma_N , intr=0.0, divr=0.0, cp_sign=cp)
        price = np.mean(price_list, axis=1)
        return price